# Generated by Django 5.1.2 on 2024-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beats/images/'),
        ),
    ]
