# Generated by Django 5.1.2 on 2024-11-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_image'),
        ('users', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='users.producer'),
        ),
    ]
