# Generated by Django 5.1.2 on 2024-11-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_beat_producer'),
        ('users', '0003_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='users.producer'),
        ),
    ]
