# Generated by Django 5.1.2 on 2024-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
