# Generated by Django 5.1.2 on 2025-02-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_producer_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='social_links',
        ),
        migrations.AddField(
            model_name='client',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beats/images/')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
